export const products = [
   {
      id: '1aa0',
      name: 'Anowa Fulali Bag',
      image: './assets/product-images/anowa-fulali-bag.jpg',
      sub_image: [
         './assets/product-images/anowa-fulali-bag-1.jpg',
         './assets/product-images/anowa-fulali-bag-2.jpg',
         './assets/product-images/anowa-fulali-bag-4.jpg',
         './assets/product-images/anowa-fulali-bag-5.jpg',
         './assets/product-images/anowa-fulali-bag-6.jpg',
         './assets/product-images/anowa-fulali-bag-7.jpg',
         './assets/product-images/anowa-fulali-bag-8.jpg',
     ],  
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'Bags',
      women: true
   },
   {
      id: '1aa1',
      name: 'Anowa Fulali Purple Leather Bag',
      image: './assets/product-images/anowa-fulali-purple-leather.jpg',
      sub_image: [
         './assets/product-images/anowa-fulali-purple-leather.jpg',
         './assets/product-images/anowa-fulali-purple-leather-2.jpg',
         './assets/product-images/anowa-fulali-bag-4.jpg',
         './assets/product-images/anowa-fulali-bag-5.jpg',
         './assets/product-images/anowa-fulali-bag-6.jpg'
     ],  
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'Bags',
      women: true
   },
   {
      id: '1aa2',
      name: 'Anowa Fulali Colored Leather Bag',
      image: './assets/product-images/anowa-fulali-bag-colored.jpg',
      sub_image: [
         './assets/product-images/anowa-fulali-purple-leather.jpg',
         './assets/product-images/anowa-fulali-purple-leather-2.jpg',
         './assets/product-images/anowa-fulali-bag-4.jpg',
         './assets/product-images/anowa-fulali-bag-5.jpg',
         './assets/product-images/anowa-fulali-bag-6.jpg'
     ],  
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'Bags',
      women: true
   },
   // anowa fulali ends here
   {
      id: '1aa3',
      name: 'Electric Blue Frayed Bag',
      image: './assets/product-images/electric-blue-frayed-bag.jpg',
      sub_image: [
         './assets/product-image/rabiyat-bag-red-2.jpg',
         './assets/product-image/rabiyat-bag-brown.jpg',
         './assets/product-image/rabiyat-bag-silver-1.jpg',
         './assets/product-image/rabiyat-bag-red-4.jpg',
      ],
      price: 550,
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'Bags',
      women: true
   },
   {
      id: '1aa4',
      name: 'Brown Rabiyat Bag',
      image: './assets/product-images/rabiyat-bag-brown.jpg',
      sub_image: [
         './assets/product-image/rabiyat-bag-red-2.jpg',
         './assets/product-image/rabiyat-bag-brown.jpg',
         './assets/product-image/rabiyat-bag-silver-1.jpg',
         './assets/product-image/rabiyat-bag-red-4.jpg',
      ],
      price: 550,
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'Bags',
      women: true
   },
   {
      id: '1aa5',
      name: 'Red Rabiyat Bag',
      image: './assets/product-images/rabiyat-bag.jpg',
      sub_image: [
         './assets/product-image/rabiyat-bag-red-2.jpg',
         './assets/product-image/rabiyat-bag-brown.jpg',
         './assets/product-image/rabiyat-silver-1.jpg',
         './assets/product-image/rabiyat-bag-red-4.jpg',
      ],
      price: 550,
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'Bags',
      women: true
   },
   {
      id: '1aa5',
      name: 'Red Rabiyat Bag',
      image: './assets/product-images/rabiyat-bag.jpg',
      sub_image: [
         './assets/product-image/rabiyat-bag-red-2.jpg',
         './assets/product-image/rabiyat-bag-brown.jpg',
         './assets/product-image/rabiyat-silver-1.jpg',
         './assets/product-image/rabiyat-bag-red-4.jpg',
      ],
      price: 550,
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'Bags',
      women: true
   },
   // Rabiyat bags ends here

   {
      id: '1aa7',
      name: 'Saris Brown Bag',
      image: './assets/product-images/saris-bag-brown.jpg',
      sub_image: [
         './assets/product-image/saris-bag-brown-1',
         './assets/product-image/saris-bag-brown-2',
         './assets/product-image/saris-bag-brown',
         './assets/product-image/rabiyat-sliver-4.jpg',
      ],
      price: 550,
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'Bags',
      women: true
   },

   {
      id: '1aa3',
      name: 'Duo Bow Slippers',
      image: './assets/product-images/duo-bow-slipper1.jpeg',
      sub_image: [
         './assets/product-images/duo-bow-plain-black-green-1.jpeg',
         './assets/product-images/duo-bow-plain-black-green-3.jpeg',
         './assets/product-images/duo-bow-plain-brown.jpeg',
         './assets/product-images/duo-bow-plain-all1.jpeg',
         './assets/product-images/duo-bow-plain-all2.jpeg',
         './assets/product-images/duo-bow-plain-all4.jpeg',
         './assets/product-images/duo-bow-plain-brown-1.jpeg',
         './assets/product-images/duo-bow-plain-green-orange-1.jpeg',
         './assets/product-images/duo-bow-plain-green-orange-2.jpeg',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: true
   },
   {
      id: '1aa4',
      name: 'Duo Bow Slippers Black Green',
      image: './assets/product-images/duo-bow-plain-black-green.jpg',
      sub_image: [
         './assets/product-images/duo-bow-plain-black-green-1.jpg',
         './assets/product-images/duo-bow-plain-black-green-2.jpg',
         './assets/product-images/duo-bow-plain-black-green-3.jpg',
         './assets/product-images/duo-bow-plain-black-green-4.jpg',
         './assets/product-images/duo-bow-plain-green-orange-1.jpeg',
         './assets/product-images/duo-bow-plain-green-orange-2.jpeg',
         './assets/product-images/duo-bow-plain-all1.jpeg',
         './assets/product-images/duo-bow-plain-all2.jpeg',
         './assets/product-images/duo-bow-plain-all4.jpeg',
      
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: true
   },
   {
      id: '1aa5',
      name: 'Duo Bow Slippers Brown',
      image: './assets/product-images/duo-bow-plain-brown.jpg',
      sub_image: [
         './assets/product-images/duo-bow-plain-brown-2.jpeg',
         './assets/product-images/duo-bow-plain-brown-1.jpeg',
         './assets/product-images/duo-bow-plain-brown-3.jpeg',
         './assets/product-images/duo-bow-plain-brown-4.jpeg',
         './assets/product-images/duo-bow-plain-brown-5.jpeg',
         './assets/product-images/duo-bow-plain-brown-6.jpeg',
         './assets/product-images/duo-bow-plain-brown-7.jpeg',
         './assets/product-images/duo-bow-plain-brown-8.jpeg',
         './assets/product-images/duo-bow-plain-all1.jpeg',
         './assets/product-images/duo-bow-plain-all2.jpeg',
         './assets/product-images/duo-bow-plain-all4.jpeg',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: true
   },
   {
      id: '1aa6',
      name: 'Duo Bow Slippers Orage Green',
      image: './assets/product-images/duo-bow-plain-green-orange.jpg',
      sub_image: [
         './assets/product-images/duo-bow-plain-green-orange-2.jpeg',
         './assets/product-images/duo-bow-plain-green-orange-3.jpeg',
         './assets/product-images/duo-bow-plain-green-orange-4.jpeg',
         './assets/product-images/duo-bow-plain-green-orange-5.jpeg',
         './assets/product-images/duo-bow-plain-all1.jpeg',
         './assets/product-images/duo-bow-plain-all2.jpeg',
         './assets/product-images/duo-bow-plain-all4.jpeg',
         './assets/product-images/duo-bow-plain-green-orange-6.jpeg',
         './assets/product-images/duo-bow-plain-green-orange-7.jpeg',
         './assets/product-images/duo-bow-plain-green-orange-8.jpeg',
         './assets/product-images/duo-bow-plain-green-orange-1.jpeg',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: true
   },
   {
      id: '1aa7',
      name: 'Duo Bow Slippers Green',
      image: './assets/product-images/duo-bow-plain-slippers-green.jpg',
      sub_image: [
         './assets/product-images/duo-bow-plain-slippers-green-1.jpeg',
         './assets/product-images/duo-bow-plain-slippers-green-2.jpeg',
         './assets/product-images/duo-bow-plain-all1.jpeg',
         './assets/product-images/duo-bow-plain-all2.jpeg',
         './assets/product-images/duo-bow-plain-all4.jpeg',
         './assets/product-images/duo-bow-plain-slippers-green-4.jpeg',
         './assets/product-images/duo-bow-plain-slippers-green.jpeg',
         './assets/product-images/duo-bow-slippers1.jpeg',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: true
   },
   {
      id: '1aa8',
      name: 'Duo Bow Plain Slippers',
      image: './assets/product-images/duo-bow-plain-1a.jpg',
      sub_image: [
         './assets/product-images/duo-bow-plain-1a1.jpeg',
         './assets/product-images/duo-bow-plain-1a2.jpeg',
         './assets/product-images/duo-bow-plain-1a3.jpeg',
         './assets/product-images/duo-bow-plain-1a4.jpeg',
         './assets/product-images/duo-bow-plain-all1.jpeg',
         './assets/product-images/duo-bow-plain-all2.jpeg',
         './assets/product-images/duo-bow-plain-all4.jpeg',
         './assets/product-images/duo-bow-plain-1a5.jpeg',
         './assets/product-images/duo-bow-plain-1a6.jpeg',
         './assets/product-images/duo-bow-plain-1a7.jpeg',
         './assets/product-images/duo-bow-plain-1a8.jpeg',
         './assets/product-images/duo-bow-plain-1a9.jpeg',
         './assets/product-images/duo-bow-plain-1a11.jpeg',
         
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: true
   },
   {
      id: '1aa9',
      name: 'Duo Bow Plain Slippers',
      image: './assets/product-images/duo-bow-plain-1b.jpg',
      sub_image: [
         './assets/product-images/duo-bow-plain-1b1.jpeg',
         './assets/product-images/duo-bow-plain-1b2.jpeg',
         './assets/product-images/duo-bow-plain-1b3.jpeg',
         './assets/product-images/duo-bow-plain-1b4.jpeg',
         './assets/product-images/duo-bow-plain-1b5.jpeg',
         './assets/product-images/duo-bow-plain-1b6.jpeg',
         './assets/product-images/duo-bow-plain-1b7.jpeg',
         './assets/product-images/duo-bow-plain-1b8.jpeg',
         './assets/product-images/duo-bow-plain-1b9.jpeg',
         './assets/product-images/duo-bow-plain-all1.jpeg',
         './assets/product-images/duo-bow-plain-all2.jpeg',
         './assets/product-images/duo-bow-plain-all4.jpeg',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: true
   },
   {
      id: '1aa10',
      name: 'Duo Bow Plain Slippers',
      image: './assets/product-images/duo-bow-plain-1c.jpg',
      sub_image: [
         './assets/product-images/duo-bow-plain-1c1.jpeg',
         './assets/product-images/duo-bow-plain-1c2.jpeg',
         './assets/product-images/duo-bow-plain-1c3.jpeg',
         './assets/product-images/duo-bow-plain-1c4.jpeg',
         './assets/product-images/duo-bow-plain-1c5.jpeg',
         './assets/product-images/duo-bow-plain-1c6.jpeg',
         './assets/product-images/duo-bow-plain-1c7.jpeg',
         './assets/product-images/duo-bow-plain-1c8.jpeg',
         './assets/product-images/duo-bow-plain-1c9.jpeg',
         './assets/product-images/duo-bow-plain-1c10.jpeg',
         './assets/product-images/duo-bow-plain-1c11.jpeg',
         './assets/product-images/duo-bow-plain-1c12.jpeg',
         './assets/product-images/duo-bow-plain-1c13.jpeg',
         './assets/product-images/duo-bow-plain-all1.jpeg',
         './assets/product-images/duo-bow-plain-all2.jpeg',
         './assets/product-images/duo-bow-plain-all4.jpeg',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: true
   },
   {
      id: '1aa11',
      name: 'Duo Bow Plain Slippers',
      image: './assets/product-images/duo-bow-plain-1d.jpg',
      sub_image: [
         './assets/product-images/duo-bow-plain-1d1.jpeg',
         './assets/product-images/duo-bow-plain-1d2.jpeg',
         './assets/product-images/duo-bow-plain-1d3.jpeg',
         './assets/product-images/duo-bow-plain-1d4.jpeg',
         './assets/product-images/duo-bow-plain-1d5.jpeg',
         './assets/product-images/duo-bow-plain-1d6.jpeg',
         './assets/product-images/duo-bow-plain-1d7.jpeg',
         './assets/product-images/duo-bow-plain-1d8.jpeg',
         './assets/product-images/duo-bow-plain-1d9.jpeg',
         './assets/product-images/duo-bow-plain-1d10.jpeg',
         './assets/product-images/duo-bow-plain-1d11.jpeg',
         './assets/product-images/duo-bow-plain-1d12.jpeg',
         './assets/product-images/duo-bow-plain-1d13.jpeg',
         './assets/product-images/duo-bow-plain-all1.jpeg',
         './assets/product-images/duo-bow-plain-all2.jpeg',
         './assets/product-images/duo-bow-plain-all4.jpeg',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: true
   },
   {
      id: '1aa12',
      name: 'Duo Bow Plain Slippers',
      image: './assets/product-images/duo-bow-plain-1e.jpg',
      sub_image: [
         './assets/product-images/duo-bow-plain-1d1.jpeg',
         './assets/product-images/duo-bow-plain-1d2.jpeg',
         './assets/product-images/duo-bow-plain-1c3.jpeg',
         './assets/product-images/duo-bow-plain-1c4.jpeg',
         './assets/product-images/duo-bow-plain-1a5.jpeg',
         './assets/product-images/duo-bow-plain-1b6.jpeg',
         './assets/product-images/duo-bow-plain-1a7.jpeg',
         './assets/product-images/duo-bow-plain-1b8.jpeg',
         './assets/product-images/duo-bow-plain-1d9.jpeg',
         './assets/product-images/duo-bow-plain-1d10.jpeg',
         './assets/product-images/duo-bow-plain-all1.jpeg',
         './assets/product-images/duo-bow-plain-all2.jpeg',
         './assets/product-images/duo-bow-plain-all4.jpeg',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: true
   },
   // end of duo bow plain slippers

   {
      id: '1aa13',
      name: 'Cross Cross Slippers',
      image: './assets/product-images/cross-cross-slippers-1.jpg',
      sub_image: [
         './assets/cross-cross-slippers-1.jpg',
         './assets/product-images/cross-cross-slippers-2.jpg',
         './assets/product-images/cross-cross-slippers-3.jpg',
         './assets/product-images/cross-cross-slippers-4.jpg',
         './assets/product-images/cross-cross-slippers-5.jpg',
         './assets/product-images/cross-cross-slippers-6.jpg',
         './assets/product-images/cross-cross-slippers-7.jpg',
         './assets/product-images/cross-cross-slippers-8.jpg',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: false
   },
   {
      name: 'Brassiere Criss Cross Slippers',
      image: './assets/product-images/brassiere-criss-cross-slippers.jpg',
      sub_image: [
         './assets/product-images/brassiere-criss-cross-slippers-1.jpg',
         './assets/product-images/brassiere-criss-cross-slippers-2.jpg',
         './assets/product-images/brassiere-criss-cross-slippers-3.jpg',
         './assets/product-images/brassiere-criss-cross-slippers-4.jpg',
         './assets/product-images/brassiere-criss-cross-slippers-5.jpg',
         './assets/product-images/brassiere-criss-cross-slippers-6.jpg',
         './assets/product-images/brassiere-criss-cross-slippers-7.jpg',
         './assets/product-images/brassiere-criss-cross-slippers-8.jpg',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: false
   },
   {
      name: 'Full band Slippers',
      image: './assets/product-images/full-band-slippers.jpg',
      sub_image: [
         './assets/product-images/full-band-slippers.jpg-1',
         './assets/product-images/full-band-slippers.jpg-2',
         './assets/product-images/full-band-slippers.jpg-3',
         './assets/product-images/full-band-slippers.jpg-4',
         './assets/product-images/full-band-slippers.jpg-5',
         './assets/product-images/full-band-slippers.jpg-6',
         './assets/product-images/full-band-slippers.jpg-7',
         './assets/product-images/full-band-slippers.jpg-8',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: false
   },
   {
      name: 'Coconut husk double bow',
      image: './assets/product-images/Coconut-HUSK-double-bow.jpg',
      sub_image: [
          './assets/product-images/Coconut-HUSK-double-bow-1.jpg',
          './assets/product-images/Coconut-HUSK-double-bow-2.jpg',
          './assets/product-images/Coconut-HUSK-double-bow-3.jpg',
          './assets/product-images/Coconut-HUSK-double-bow-4.jpg',
          './assets/product-images/Coconut-HUSK-double-bow-5.jpg',
          './assets/product-images/Coconut-HUSK-double-bow-6.jpg',
          './assets/product-images/Coconut-HUSK-double-bow-7.jpg',
          './assets/product-images/Coconut-HUSK-double-bow=8.jpg',
          './assets/product-images/Coconut-HUSK-double-bow-9.jpg',
      ], 
      price: 550, 
      size: [40, 41, 42, 43, 45, 47, 48, 49], 
      category: 'slippers',
      women: true
   },
  

]